config/routes.rb
Twitterfeed::Application.routes.draw do
  resources :users
  resources :user_sessions
  resources :users do
    post 'tweet', :on => :collection
  end
  get "home/index"

  match "logout" => 'user_sessions#destroy'

  match "/auth/:provider/callback", :controller => "authorizations", :action => "create"
  match "/auth/failure", :controller => "authorizations", :action => "failure"

   root :to => 'home#index'

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
    validates_presence_of :user_id, :uid, :provider
    validates_uniqueness_of :uid, :scope => :provider

    def self.find_from_hash(hash)
    puts "in authorization find_from"
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    puts "in authorization create_from"
    user ||= User.create_from_hash(hash)
    Authorization.create(:user_id => user.id, :uid => hash['uid'], :provider => hash['provider'],:token=> hash ['credentials']['token'],:secret => hash ['credentials']['secret'])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic

  has_many :authorizations, :dependent => :destroy

  def self.create_from_hash(hash)
    create(:name => hash['user_info']['name'])
  end

  def self.create_from_hash(hash)
    puts "in user.rb"
    user = User.new(:name => hash['user_info']['name'])
    puts user.name
    puts user.valid?
    if user.save(:validate => false) #create the user without performing validations. This is because most of the fields are not set.
    puts "user saved in user.rb"
    else
    puts "not saved"
    end
    puts user.name
    user.reset_persistence_token! #set persistence_token else sessions will not be created
    user
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  authenticate_with User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  private

    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to :controller => "user_sessions",:action =>"new" # halts request cycle
      end
    end

    def logged_in?
      !!current_user
    end

end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
   before_filter :require_login, :only => [:destroy]

  def create
    omniauth = request.env['omniauth.auth'] #this is where you get all the data from your provider through omniauth
    @auth = Authorization.find_from_hash(omniauth)
    if current_user
      flash[:notice] = "Successfully added #{omniauth['provider']} authentication"
      current_user.authorizations.create(:provider => omniauth['provider'], :uid => omniauth['uid']) #Add an auth to existing user
    elsif @auth
      flash[:notice] = "Welcome back #{omniauth['provider']} user"
      #create session
      @auth.update_attributes(:token => omniauth['credentials']['token'] ,:secret =>omniauth['credentials']['secret'])
      UserSession.create(@auth.user, true) # if you are using authlogic, this will create the session
      #consumer = OAuth::Consumer.new("mshsD0jpgcYwwOEcTW5ZTA", "V6KTqllY5jS392pj4FNFCb5EiOM8DaFzVwr9cS54XQ", { :site => "https://api.twitter.com", :request_token_path => '/oauth/request_token', :access_token_path => '/oauth/access_token', :authorize_path => '/oauth/authorize', :scheme => :header })
      #access_token = OAuth::AccessToken.new(consumer,omniauth['credentials']['token'],omniauth['credentials']['secret'])
      #msg = {'status' => 'Hey look I can tweet via OAuth!'}
      #response = access_token.post('https://api.twitter.com/1/statuses/update.json', msg, { 'Accept' => 'application/xml' })
      #puts response
      #User is present. Login the user with his social account
    else
      @new_auth = Authorization.create_from_hash(omniauth, current_user) #Create a new user
      flash[:notice] = "Welcome #{omniauth['provider']} user. Your account has been created."
      #create session
      UserSession.create(@new_auth.user, true) # if you are using authlogic, this will create the session
    end
    redirect_to root_url
  end

  def failure
    flash[:notice] = "Sorry, You din't authorize"
    redirect_to root_url
  end

  def destroy
    @authorization = current_user.authorizations.find(params[:id])
    flash[:notice] = "Successfully deleted #{@authorization.provider} authentication."
    @authorization.destroy
    redirect_to profile_path(current_user.username)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  before_filter :require_login, :except => [:new, :create]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to root_url
    else
    render :action => "new"
    end
  end

  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def tweet
    @message = params[:message]
    puts @message.class
    if current_user.authorizations.empty?
    else
      auth = Authorization.find_by_user_id(current_user.id)
      consumer = OAuth::Consumer.new("mshsD0jpgcYwwOEcTW5ZTA", "V6KTqllY5jS392pj4FNFCb5EiOM8DaFzVwr9cS54XQ", { :site => "https://api.twitter.com", :request_token_path => '/oauth/request_token', :access_token_path => '/oauth/access_token', :authorize_path => '/oauth/authorize', :scheme => :header })
        access_token = OAuth::AccessToken.new(consumer,auth.token,auth.secret)
        msg = {'status' => @message}
        response = access_token.post('https://api.twitter.com/1/statuses/update.json', msg, { 'Accept' => 'application/xml' })
    end
  end
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% flash.each do |key, msg| %>
  <div class="alert-message success">
  <%= content_tag :div, msg, :id => key %>
  </div>
<% end %>
<% content_for :head do %>
  <title>Twitter App</title>
<% end %>
<% content_for :pagename do %>
  Twitter App
<% end %>
<% if current_user %>

  <%if current_user.authorizations.empty? %>

  <%else%>
    <%= form_tag "/users/tweet", :method => 'post',:id=>"form_tweet" do %>
    <%= text_area_tag(:message) %>
    <input type=submit id="codecheck" value="tweet" class="btn primary">
    <div id="status" style= "float:right;padding:0px 275px 0px 0px"></div>
  <% end %>

    <%auth = Authorization.find_by_user_id(current_user.id)%>
    <%consumer = OAuth::Consumer.new("mshsD0jpgcYwwOEcTW5ZTA", "V6KTqllY5jS392pj4FNFCb5EiOM8DaFzVwr9cS54XQ", { :site => "https://api.twitter.com", :request_token_path => '/oauth/request_token', :access_token_path => '/oauth/access_token', :authorize_path => '/oauth/authorize', :scheme => :header })%>
    <%access_token = OAuth::AccessToken.new(consumer,auth.token,auth.secret)%>
    <% msg = {'count' => 10} %>
    <% response = access_token.get('https://api.twitter.com/1/statuses/home_timeline.json?count=10',{ 'Accept' => 'application/xml' }).body %>
    <%tweets = JSON.parse(response)%>
    <% tweets.each do |tweet| %>
      <% addr = "https://twitter.com/#!/"+tweet["user"]["screen_name"]%>
      <h3><a href= <%= addr %> ><%= tweet["user"]["screen_name"]%></a></h3>
      <h3><%= tweet["text"]%></h3>
      <% if tweet["text"].include?"http"%>
        <h3>found http</h3>
        <h3><a href= <%= tweet["text"].scan(/\bhttp\b[a-zA-Z0-9\/.:]+/)[0] %> ><%= tweet["text"].scan(/\bhttp\b[a-zA-Z0-9\/.:]+/)[0] %> </a></h3>
        <% uri = URI.parse(tweet["text"].scan(/\bhttp\b[a-zA-Z0-9\/.:]+/)[0]) %>
    <% response = Net::HTTP.get_response(uri) %>
    <% while response.code == "301"%>
      <% url = response.header['location'] %>
      <% url = URI.encode(url)%>
      <% Rails.logger.debug response.code.inspect%>
      <% uri = URI.parse(url) %>
      <% response = Net::HTTP.get_response(uri) %>
    <% end %>
        <h3>Actual URL is</h3>
        <h3><a href = <%=url%>><%=url%></h3></a>
       <% Rails.logger.debug response.code.inspect%>
       <% doc = Hpricot(response.body) %>
       <h3><%= doc.search("//title").inner_html %></h3>
      <%end%>
    <%end%>
  <%end%>
<%end%>

<script type="text/javascript">
  $(document).ready(function () {
    $("#form_tweet").submit(function(e){
        $("#status").html("<img src='/assets/ajax-loader.gif'/>")
        e.preventDefault()
          $.ajax({
            url: $('#form_tweet').attr('action'),
            complete: function() {
              $("#status").html("")
              alert("Tweet successfully posted")
            },
            dataType: "script",
            type: "post",
            data: $('#form_tweet').serialize()
          })
      })
  })
</script>

app/views/layouts/_header.html.erb
<div class="topbar">
  <div class="fill">
    <div class="container">
      <%= link_to "Git Chat",root_url,:class => "brand" %>
      <ul class="nav">
        <% if current_user %>
          <li><%= link_to "Signout",logout_path%></li>
        <% else %>
          <li><%= link_to 'Sign In', {:controller=> "user_sessions", :action=> "new"},:class => "signin" %></li>
          <li><%= link_to 'Sign Up',new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= yield :head %>
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_include_tag "jquery-1.7.1" %>
  </head>

  <body>
      <%= render 'layouts/header' %>
    <div class="container">
    <div class="content">
    <div class="page-header">
      <h1><%= yield :pagename %></h1>
    </div>
    <div class="row">
      <div class="span10">
        <%= yield %>
      </div>
      <div class="span4">
      </div>
    </div>
    </div>

    <footer>
    <p>&copy; Company 2011</p>
    </footer>
    </body>
</html>

app/views/user_sessions/new.html.erb
<div class="user-form">
<h1>Login</h1>
<%= form_for @user_session, :url => { :action => "create" } do |f| %>

  <% if @user_session.errors.full_messages[0] %>
    <ul class="alert-message block-message error">
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class = "error">
  </div>
  <div class="clearfix">
    <%= f.label :email %>
    <div class="input">
      <%= f.text_field :email %>
    </div>
  </div>
  <br />
  <div class="clearfix">
    <%= f.label :password %>
    <div class="input">
      <%= f.password_field :password %>
    </div>
  </div>
  <br />
  <div class="actions">
  <%= f.submit "Login", :class=>"btn primary" %>
  </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="user-form1">
<%= form_for(@user) do |f| %>
  <% if @user.errors.full_messages[0] %>
    <ul class="alert-message block-message error">
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="clearfix">
    <%= f.label :name %>
    <div class="input">
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :email %>
    <div class="input">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :password %>
    <div class="input">
     <%= f.password_field :password %>
    </div>
  </div>
  <div class="clearfix">
    <%= f.label :password_confirmation %>
    <div class="input">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit :class=>"btn primary" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>